### ISSUE TITLE
Django 2.2

### ISSUE THREAD

**Issue by hugokernel** [WimpyAnalytics/django-andablog#64]
Hi,
Is the support of Django 2 planned?
Thx

**Comment by ivanvenosdel** [comment]
The project already supports up to Django 2.1. It may work with Django 2.2 as well but I haven't tried it. The easiest way to tell would be to clone the project, add an entry for 2.2 to the tox.ini and run "tox -e" for that environment.

Otherwise I should get some time to look into it in a couple months.
