### ISSUE TITLE
Invalid default_markup_type for field 'None', allowed values: html, plain

### ISSUE THREAD

**Issue by hyances** [WimpyAnalytics/django-andablog#66]
Hi!  I'm just doing a fresh install over Django 2.2 project, after run:

`$ ./manage.py migrate`

I got this:

`lib/python3.6/site-packages/markupfield/fields.py", line 125, in __init__
    "allowed values: %s" % (name, ", ".join(self.markup_choices_list))
ValueError: Invalid default_markup_type for field 'None', allowed values: html, plain
`
What I'm doing wrong?

**Comment by ivanvenosdel** [comment]
I was able to reproduce your error by uninstalling the Markdown package from the demo site and then rebuilding the db (which includes migrate). So if you don't mind using markdown for your blog posts then the problem is that your project needs the Markdown package to be installed.

For background, django-andablog uses django-markupfield for rendering blog text to html. With that project you either need to have Markdown (the package) installed or you need to set [MARKUP_FIELD_TYPES](https://github.com/jamesturk/django-markupfield#settings) to something custom.

**Comment by hyances** [comment]
Thanks!  Install Markdown package resolve the issue.
